#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=stingray
MANUFACTURER=moto
EXT_F=EXTRACT_ROM_FILES

prop_list="system/bin/akmd2 \
system/bin/batch \
system/bin/brcm_guci_drv \
system/bin/bugtogo.sh \
system/bin/bypassfactory \
system/bin/ftmipcd \
system/bin/location \
system/bin/savebpver \
system/bin/tcmd \
system/etc/cpcap_gain.bin \
system/etc/firmware/bcm4329.hcd \
system/etc/firmware/nvddk_audiofx_core.axf \
system/etc/firmware/nvddk_audiofx_transport.axf \
system/etc/firmware/nvmm_aacdec.axf \
system/etc/firmware/nvmm_adtsdec.axf \
system/etc/firmware/nvmm_audiomixer.axf \
system/etc/firmware/nvmm_h264dec.axf \
system/etc/firmware/nvmm_jpegdec.axf \
system/etc/firmware/nvmm_jpegenc.axf \
system/etc/firmware/nvmm_manager.axf \
system/etc/firmware/nvmm_mp2dec.axf \
system/etc/firmware/nvmm_mp3dec.axf \
system/etc/firmware/nvmm_mpeg4dec.axf \
system/etc/firmware/nvmm_reference.axf \
system/etc/firmware/nvmm_service.axf \
system/etc/firmware/nvmm_sorensondec.axf \
system/etc/firmware/nvmm_sw_mp3dec.axf \
system/etc/firmware/nvmm_wavdec.axf \
system/etc/firmware/nvrm_avp.bin \
system/etc/gps.conf \
system/etc/gpsconfig.xml \
system/etc/location.cfg \
system/etc/motorola/12m/key_code_map.txt \
system/etc/motorola/12m/tcmd_leds.cfg \
system/etc/security/suplcerts.bks \
system/etc/voip_aud_params.bin \
system/etc/wifi/bcm4329.cal \
system/lib/egl/libEGL_perfhud.so \
system/lib/egl/libEGL_tegra.so \
system/lib/egl/libGLESv1_CM_perfhud.so \
system/lib/egl/libGLESv1_CM_tegra.so \
system/lib/egl/libGLESv2_perfhud.so \
system/lib/egl/libGLESv2_tegra.so \
system/lib/hw/camera.stingray.so \
system/lib/hw/gps.stingray.so \
system/lib/hw/gralloc.tegra.so \
system/lib/hw/hwcomposer.tegra.so \
system/lib/libcgdrv.so \
system/lib/libdmengine.so \
system/lib/libdmjavaplugin.so \
system/lib/libims_client_jni.so \
system/lib/libmoto_ecnswrapper.so \
system/lib/libnvddk_2d.so \
system/lib/libnvddk_2d_v2.so \
system/lib/libnvddk_audiofx.so \
system/lib/libnvdispatch_helper.so \
system/lib/libnvdispmgr_d.so \
system/lib/libnvmm.so \
system/lib/libnvmm_camera.so \
system/lib/libnvmm_contentpipe.so \
system/lib/libnvmm_image.so \
system/lib/libnvmm_manager.so \
system/lib/libnvmm_service.so \
system/lib/libnvmm_tracklist.so \
system/lib/libnvmm_utils.so \
system/lib/libnvmm_video.so \
system/lib/libnvodm_imager.so \
system/lib/libnvodm_query.so \
system/lib/libnvomx.so \
system/lib/libnvomxilclient.so \
system/lib/libnvos.so \
system/lib/libnvrm.so \
system/lib/libnvrm_channel.so \
system/lib/libnvrm_graphics.so \
system/lib/libnvsm.so \
system/lib/libnvwsi.so \
system/lib/libpkip.so \
system/lib/libstagefrighthw.so \
system/lib/libtpa.so \
system/lib/libtpa_core.so \
system/media/bootanimation-encrypted.zip \
system/media/bootanimation.zip \
system/vendor/etc/audio_effects.conf \
system/vendor/firmware/fw_bcm4329_mfg.bin"

prop_apk_list="system/app/AppDirectedSmsService.apk \
system/app/ConnMO.apk \
system/app/DMService.apk \
system/app/MotoImsServer.apk \
system/app/MotoLocationProxy.apk \
system/app/MotoLteTelephony.apk \
system/app/MotoModemUtil.apk \
system/app/MotoSimUiHelper.apk \
system/app/StingrayProgramMenu.apk \
system/app/StingrayProgramMenuSystem.apk \
system/app/UsbHelper.apk"

chmod_list=""

pull_adb_files() {
for x in ${prop_list} ${prop_apk_list}; do
        echo "Pulling ${x} from adb connection now..."
        adb pull /${x} ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/
done

cchm=$(echo ${chmod_list} |wc -w)
if [ ${cchm} -gt 0 ]; then
for x in ${chmod_list}; do
        s=$(echo "$x" |awk -F/ '{print $NF}')
        echo "Fixing permissions for ${x} from now..."
        chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/${s}
done
fi
}

pull_zip_files() {
if [ -d ${EXT_F} ]; then
        rm -rf ${EXT_F}
fi
unzip ${ZIP} -d ${EXT_F}

for x in ${prop_list} ${prop_apk_list}; do
        echo "Copying ${x} from ${ZIP} now..."
        cp ${EXT_F}/${x} ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/
done

cchm=$(echo ${chmod_list} |wc -w)
if [ ${cchm} -gt 0 ]; then
for x in ${chmod_list}; do
        s=$(echo "$x" |awk -F/ '{print $NF}')
        echo "Fixing permissions for ${s} from now..."
        chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/${s}
done
fi
}

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary

if [ $# -eq  0 ]; then
        pull_adb_files
elif [ $# -eq 1 ]; then
        ZIP="${1}"
        pull_zip_files
else
        echo "Error: Too many arguments. Wanted 1 got $#"
        exit 1
fi

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# All the apks necessary for stingray
PRODUCT_PACKAGES += \\
    AppDirectedSmsService \\
    ConnMO \\
    DMService \\
    MotoImsServer \\
    MotoLocationProxy \\
    MotoLteTelephony \\
    MotoModemUtil \\
    MotoSimUiHelper \\
    StingrayProgramMenu \\
    StingrayProgramMenuSystem \\
    UsbHelper

# All the blobs necessary for crespo4g
PRODUCT_COPY_FILES += \\
EOF
chk_count=$(echo ${prop_list} |wc -w)
COUNT=0
for x in ${prop_list}; do
        COUNT=`expr ${COUNT} + 1`
        s=$(echo "$x" |awk -F/ '{print $NF}')
        if [ ${COUNT} -eq ${chk_count} ]; then
                echo "    vendor/$MANUFACTURER/$DEVICE/proprietary/${s}:${x}" >> ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
        else
                echo "    vendor/$MANUFACTURER/$DEVICE/proprietary/${s}:${x} \\" >> ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
        fi
done

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/Android.mk
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

ifeq (\$(TARGET_DEVICE),stingray)
LOCAL_PATH:=\$(call my-dir)

# Module makefile rules for apks on stingray

# AppDirectedSmsService

include \$(CLEAR_VARS)

LOCAL_MODULE := AppDirectedSmsService
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# ConnMO

include \$(CLEAR_VARS)

LOCAL_MODULE := ConnMO
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# DMService

include \$(CLEAR_VARS)

LOCAL_MODULE := DMService
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# MotoImsServer

include \$(CLEAR_VARS)

LOCAL_MODULE := MotoImsServer
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# MotoLocationProxy

include \$(CLEAR_VARS)

LOCAL_MODULE := MotoLocationProxy
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# MotoLteTelephony

include \$(CLEAR_VARS)

LOCAL_MODULE := MotoLteTelephony
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# MotoModemUtil

include \$(CLEAR_VARS)

LOCAL_MODULE := MotoModemUtil
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# MotoSimUiHelper

include \$(CLEAR_VARS)

LOCAL_MODULE := MotoSimUiHelper
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# StingrayProgramMenu

include \$(CLEAR_VARS)

LOCAL_MODULE := StingrayProgramMenu
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# StingrayProgramMenuSystem

include \$(CLEAR_VARS)

LOCAL_MODULE := StingrayProgramMenuSystem
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# UsbHelper

include \$(CLEAR_VARS)

LOCAL_MODULE := UsbHelper
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

endif

EOF

./setup-makefiles.sh
